name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y openssl
          chmod +x test.sh
          sudo ./test.sh